(function () {
  const BOARD_BASE_URL = 'http://127.0.0.1:5181/';
  const PROJECT_IDS = new Set([
    'hapa-app-consul-node-proto',
    'hapa-app-cymatica',
    'hapa-app-hapa',
    'hapa-app-hapa-ac',
    'hapa-app-hapa-agent-registry-node',
    'hapa-app-hapa-anvil-node',
    'hapa-app-hapa-artifacts',
    'hapa-app-hapa-avatar-dashboard',
    'hapa-app-hapa-avatar-node',
    'hapa-app-hapa-avatar-skill-cms',
    'hapa-app-hapa-avatars-pose-references',
    'hapa-app-hapa-card-relationship-lab',
    'hapa-app-hapa-chat-app',
    'hapa-app-hapa-crypto-node',
    'hapa-app-hapa-cu',
    'hapa-app-hapa-cultivation-suite',
    'hapa-app-hapa-dash',
    'hapa-app-hapa-dev-proto',
    'hapa-app-hapa-drama',
    'hapa-app-hapa-engines',
    'hapa-app-hapa-exports-staging',
    'hapa-app-hapa-janus-world-node',
    'hapa-app-hapa-keys-node',
    'hapa-app-hapa-lance-node',
    'hapa-app-hapa-lito',
    'hapa-app-hapa-living-comic',
    'hapa-app-hapa-llada-node',
    'hapa-app-hapa-lore-intro-video',
    'hapa-app-hapa-lore-node',
    'hapa-app-hapa-luminastem-station',
    'hapa-app-hapa-media-snapshot-12-25-2025',
    'hapa-app-hapa-mlx-station',
    'hapa-app-hapa-og',
    'hapa-app-hapa-open-tasks-node',
    'hapa-app-hapa-opportunity-node',
    'hapa-app-hapa-overwatch-kanban',
    'hapa-app-hapa-production-runs',
    'hapa-app-hapa-proto-dev-alpha-oh-hi-m',
    'hapa-app-hapa-second-brain',
    'hapa-app-hapa-skills-app',
    'hapa-app-hapa-song-registry',
    'hapa-app-hapa-spaceship-desktop-hijack',
    'hapa-app-hapa-spec-scaffold',
    'hapa-app-hapa-sprite-development',
    'hapa-app-hapa-telemetry-node',
    'hapa-app-hapa-trellis',
    'hapa-app-hapa-video',
    'hapa-app-hapa-wiki-growth-agent',
    'hapa-app-hapa-wiki-viewer',
    'hapa-app-hapa-worldbuilding-wiki',
    'hapa-app-help-fund-hapa-capsule',
    'hapa-app-overwatch',
    'hapa-black-horizon-mvp',
    'hapa-ecosystem-packaging-quest',
    'hapa-quest-keeper',
    'qwen-creative-writer-agent',
  ]);
  const ALIASES = {
    'consul-node-proto': 'hapa-app-consul-node-proto',
    cymatica: 'hapa-app-cymatica',
    hapa: 'hapa-app-hapa',
    'hapa-ac': 'hapa-app-hapa-ac',
    'hapa-agent-registry-node': 'hapa-app-hapa-agent-registry-node',
    'hapa-ai-model-chat': 'hapa-app-hapa-chat-app',
    'hapa-anvil-node': 'hapa-app-hapa-anvil-node',
    'hapa-artifacts': 'hapa-app-hapa-artifacts',
    'hapa-atlas': 'hapa-app-hapa-dev-proto',
    'hapa-avatar-dashboard': 'hapa-app-hapa-avatar-dashboard',
    'hapa-avatar-node': 'hapa-app-hapa-avatar-node',
    'hapa-avatar-skill-cms': 'hapa-app-hapa-avatar-skill-cms',
    'hapa-avatars-pose-references': 'hapa-app-hapa-avatars-pose-references',
    'hapa-chat-app': 'hapa-app-hapa-chat-app',
    'hapa-crypto-node': 'hapa-app-hapa-crypto-node',
    'hapa-cu': 'hapa-app-hapa-cu',
    'hapa-cultivation-suite': 'hapa-app-hapa-cultivation-suite',
    'hapa-dash': 'hapa-app-hapa-dash',
    'hapa-dev-proto': 'hapa-app-hapa-dev-proto',
    'hapa-drama': 'hapa-app-hapa-drama',
    'hapa-engines': 'hapa-app-hapa-engines',
    'hapa-exports-staging': 'hapa-app-hapa-exports-staging',
    'hapa-forge': 'hapa-app-hapa-anvil-node',
    'hapa-game-engine': 'hapa-app-hapa-engines',
    'hapa-game-generation-node': 'hapa-app-hapa-engines',
    'hapa-janus-world-node': 'hapa-app-hapa-janus-world-node',
    'hapa-keys-node': 'hapa-app-hapa-keys-node',
    'hapa-lance-node': 'hapa-app-hapa-lance-node',
    'hapa-library': 'hapa-app-hapa-dev-proto',
    'hapa-lito': 'hapa-app-hapa-lito',
    'hapa-living-comic': 'hapa-app-hapa-living-comic',
    'hapa-llada-node': 'hapa-app-hapa-llada-node',
    'hapa-lore-intro-video': 'hapa-app-hapa-lore-intro-video',
    'hapa-lore-node': 'hapa-app-hapa-lore-node',
    'hapa-ltx-node': 'hapa-app-hapa-video',
    'hapa-luminastem-station': 'hapa-app-hapa-luminastem-station',
    'hapa-master-dashboard': 'hapa-app-hapa-dash',
    'hapa-media-node': 'hapa-app-hapa-video',
    'hapa-media-snapshot-12-25-2025': 'hapa-app-hapa-media-snapshot-12-25-2025',
    'hapa-mlx-station': 'hapa-app-hapa-mlx-station',
    'hapa-node-space': 'hapa-app-hapa',
    'hapa-og': 'hapa-app-hapa-og',
    'hapa-open-tasks-node': 'hapa-app-hapa-open-tasks-node',
    'hapa-opportunity-node': 'hapa-app-hapa-opportunity-node',
    'hapa-overwatch-kanban': 'hapa-app-hapa-overwatch-kanban',
    'hapa-production-runs': 'hapa-app-hapa-production-runs',
    'hapa-proto-dev-alpha-oh-hi-m': 'hapa-app-hapa-proto-dev-alpha-oh-hi-m',
    'hapa-prototype': 'hapa-app-hapa-dev-proto',
    'hapa-quest-keeper': 'hapa-quest-keeper',
    'hapa-second-brain': 'hapa-app-hapa-second-brain',
    'hapa-skills-app': 'hapa-app-hapa-skills-app',
    'hapa-song-registry': 'hapa-app-hapa-song-registry',
    'hapa-space': 'hapa-black-horizon-mvp',
    'hapa-spaceship-desktop-hijack': 'hapa-app-hapa-spaceship-desktop-hijack',
    'hapa-spec-scaffold': 'hapa-app-hapa-spec-scaffold',
    'hapa-sprite-development': 'hapa-app-hapa-sprite-development',
    'hapa-telemetry-node': 'hapa-app-hapa-telemetry-node',
    'hapa-thors-hamma': 'hapa-app-hapa-artifacts',
    'hapa-trellis': 'hapa-app-hapa-trellis',
    'hapa-video': 'hapa-app-hapa-video',
    'hapa-wiki-growth-agent': 'hapa-app-hapa-wiki-growth-agent',
    'hapa-wiki-viewer': 'hapa-app-hapa-wiki-viewer',
    'hapa-worldbuilding-wiki': 'hapa-app-hapa-worldbuilding-wiki',
    'help-fund-hapa-capsule': 'hapa-app-help-fund-hapa-capsule',
    overwatch: 'hapa-app-overwatch',
    'overwatch-node': 'hapa-app-overwatch',
    'pulse-node-proto-dev': 'hapa-app-hapa-cultivation-suite',
    'qwen-creative-writer-agent': 'qwen-creative-writer-agent',
    'world-building-wiki': 'hapa-app-hapa-worldbuilding-wiki',
  };

  function slug(value) {
    return String(value || '')
      .toLowerCase()
      .replace(/&/g, ' and ')
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '');
  }

  function basenameSlug(value) {
    return slug(String(value || '').split('/').pop().replace(/\.[a-z0-9]+$/i, ''));
  }

  function projectIdForNode(node = {}) {
    const candidates = [
      node.kanbanProjectId,
      node.kanban_project_id,
      ALIASES[slug(node.id)],
      ALIASES[slug(node.name)],
      ALIASES[basenameSlug(node.path)],
      slug(node.id).startsWith('hapa-') ? `hapa-app-${slug(node.id)}` : '',
      slug(node.name).startsWith('hapa-') ? `hapa-app-${slug(node.name)}` : '',
      slug(node.name) ? `hapa-app-hapa-${slug(node.name)}` : '',
      basenameSlug(node.path).startsWith('hapa-') ? `hapa-app-${basenameSlug(node.path)}` : '',
      basenameSlug(node.path) ? `hapa-app-hapa-${basenameSlug(node.path)}` : '',
      node.status === 'hapa-dev-proto app' || node.path === 'hapa-dev-proto app column' ? 'hapa-app-hapa-dev-proto' : '',
    ].filter(Boolean);
    return candidates.find((candidate) => PROJECT_IDS.has(candidate)) || '';
  }

  function boardUrl(projectId) {
    return projectId ? `${BOARD_BASE_URL}?project=${encodeURIComponent(projectId)}` : '';
  }

  window.HAPA_KANBAN_INGRESS = {
    baseUrl: BOARD_BASE_URL,
    projectIds: PROJECT_IDS,
    aliases: ALIASES,
    slug,
    projectIdForNode,
    boardUrl,
  };
}());
